In [70]:
import numpy as np
import pandas as pd

In [39]:
array1 = np.array([1,3,7])

In [40]:
array1

array([1, 3, 7])

In [41]:
type(array1)

numpy.ndarray

In [42]:
array2= np.array([ [1,8,6],
                 [2,7,3]])

In [43]:
type(array2)

numpy.ndarray

In [58]:
array3 = np.array([[
            [8,5,4],
            [3,2,1]],
            [[3,7,8],
            [6,7,8]
            ],[[3,7,8],
            [6,7,8]
            ]
])

In [59]:
type(array3)

numpy.ndarray

In [60]:
array3.ndim

3

In [61]:
array3.size

18

In [62]:
type(array1),type(array2),type(array3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [63]:
array1.size,array2.size,array3.size

(3, 6, 18)

In [64]:
print(array3)

[[[8 5 4]
  [3 2 1]]

 [[3 7 8]
  [6 7 8]]

 [[3 7 8]
  [6 7 8]]]


In [76]:
array3.shape

(3, 2, 3)

In [65]:
array4= np.array([
    
    [[3,1],[4,1]],
    [[5,2],[7,2]],
    [[9,5],[6,5]]])


In [66]:
type(array4)

numpy.ndarray

In [67]:
array4.size

12

In [68]:
array4.ndim

3

In [75]:
array3.shape


(3, 2, 3)

In [77]:
arrayData= pd.DataFrame(array2)

In [78]:
arrayData

0  1  2
0  1  8  6
1  2  7  3

In [79]:
type(arrayData)

pandas.core.frame.DataFrame

In [82]:
type(array2)

numpy.ndarray

In [84]:
type(array2[:])

numpy.ndarray

In [120]:
zeroValues=np.zeros((2,3,4))

In [121]:
type(zeroValues)

numpy.ndarray

In [122]:
zeroValues.shape

(2, 3, 4)

In [123]:
zeroValues

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [125]:
zeroDataFrame= pd.DataFrame(zeroValues[1])

In [126]:
zeroDataFrame

0    1    2    3
0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0

In [128]:
onesArray = np.ones((2,3))

In [130]:
onesArray

array([[1., 1., 1.],
       [1., 1., 1.]])

In [131]:
randomInt=np.arange(0,100,2)

In [132]:
randomInt

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [173]:
np.random.seed(90)
randomNumbers=np.random.randint(9989,45678,1)

In [174]:
randomNumbers

array([45474])

In [192]:
a1=np.array([1,3,5])

In [193]:
a1

array([1, 3, 5])

In [189]:
a2=np.ones((3))

In [190]:
a2

array([1., 1., 1.])

In [196]:
sum=a1+a2

In [198]:
sum

array([2., 4., 6.])

In [199]:
dif=a1-a2

In [200]:
dif

array([0., 2., 4.])

In [201]:
mult=a1*a2

In [202]:
mult

array([1., 3., 5.])

In [203]:
div=a1/a2

In [204]:
div

array([1., 3., 5.])

In [211]:
div= a2 // a1

In [212]:
div

array([1., 0., 0.])

In [217]:
mul2=a1**9

In [218]:
mul2

array([      1,   19683, 1953125])

In [220]:
<img src="images/kandahar.jpg"/>

SyntaxError: invalid syntax (<ipython-input-220-789fa7cb615b>, line 1)

In [1]:
from matplotlib.image import imread

In [2]:
kandahar = imread("kandahar.jpg")

In [3]:
kandahar

array([[[132, 160, 181],
        [131, 159, 180],
        [130, 158, 179],
        ...,
        [140, 168, 189],
        [140, 168, 189],
        [137, 164, 185]],

       [[133, 161, 182],
        [132, 160, 181],
        [131, 159, 180],
        ...,
        [137, 165, 186],
        [137, 165, 186],
        [146, 173, 194]],

       [[133, 161, 182],
        [133, 161, 182],
        [132, 160, 181],
        ...,
        [139, 167, 188],
        [140, 168, 189],
        [149, 176, 197]],

       ...,

       [[110, 143, 100],
        [108, 141,  98],
        [101, 133,  92],
        ...,
        [ 42,  75,  46],
        [ 40,  73,  44],
        [ 40,  76,  38]],

       [[100, 133,  90],
        [109, 142,  99],
        [116, 148, 107],
        ...,
        [ 54,  87,  60],
        [ 51,  84,  57],
        [ 50,  86,  50]],

       [[100, 133,  90],
        [109, 142,  99],
        [116, 148, 107],
        ...,
        [ 54,  86,  62],
        [ 51,  83,  59],
        [ 50,  85,  52]]

In [4]:
type(kandahar)

numpy.ndarray

In [5]:
kandahar.shape

(906, 945, 3)