In [1]:
import numpy as np
import pandas as pd

# Data Types & Attributes

In [2]:
array1 = np.array([1,3,4])

In [3]:
type(array1)

numpy.ndarray

In [4]:
array2 = np.array([[1,2,3],
                    [1,2,3],
                    [1,2.89,3.23]])

In [5]:
array2

array([[1.  , 2.  , 3.  ],
       [1.  , 2.  , 3.  ],
       [1.  , 2.89, 3.23]])

In [6]:
type(array2)

numpy.ndarray

In [7]:
array1.shape

(3,)

In [8]:
array2.shape

(3, 3)

In [9]:
array2.ndim

2

In [10]:
array1.dtype,array2.dtype


(dtype('int64'), dtype('float64'))

In [11]:
array1.size

3

In [12]:
array2.size

9

# Create a DataFrame from NumPy Array

In [13]:
import pandas as pd

In [14]:
dataframe= pd.DataFrame(array2)

In [15]:
dataframe

0     1     2
0  1.0  2.00  3.00
1  1.0  2.00  3.00
2  1.0  2.89  3.23

# Creating Arrays


In [16]:
sample_array= np.array([2,7,8])

In [17]:
sample_array

array([2, 7, 8])

In [18]:
oneArray = np.ones((2,3))

In [19]:
oneArray

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
oneArray.dtype


dtype('float64')

In [21]:
type(oneArray)

numpy.ndarray

<img src= "kandahar.jpg"/>

In [1]:
from matplotlib_image import imread

ModuleNotFoundError: No module named 'matplotlib_image'

In [2]:
from matplotlib.image import imread

In [3]:
kandahar =imread("kandahar.jpg")

In [4]:
print(kandahar)

[[[132 160 181]
  [131 159 180]
  [130 158 179]
  ...
  [140 168 189]
  [140 168 189]
  [137 164 185]]

 [[133 161 182]
  [132 160 181]
  [131 159 180]
  ...
  [137 165 186]
  [137 165 186]
  [146 173 194]]

 [[133 161 182]
  [133 161 182]
  [132 160 181]
  ...
  [139 167 188]
  [140 168 189]
  [149 176 197]]

 ...

 [[110 143 100]
  [108 141  98]
  [101 133  92]
  ...
  [ 42  75  46]
  [ 40  73  44]
  [ 40  76  38]]

 [[100 133  90]
  [109 142  99]
  [116 148 107]
  ...
  [ 54  87  60]
  [ 51  84  57]
  [ 50  86  50]]

 [[100 133  90]
  [109 142  99]
  [116 148 107]
  ...
  [ 54  86  62]
  [ 51  83  59]
  [ 50  85  52]]]


In [5]:
kandahar.shape,kandahar.size,kandahar.ndim

((906, 945, 3), 2568510, 3)

In [6]:
<img src = "images/afg.jpg"/>

SyntaxError: invalid syntax (<ipython-input-6-bdf4681c710d>, line 1)

In [8]:
afg= imread("images/afg.jpg")

In [9]:
type(afg)

numpy.ndarray

In [10]:
print(afg)

[[[  8   8   8]
  [  8   8   8]
  [  9   9   9]
  ...
  [ 14 113   5]
  [  9 107   4]
  [  8 106   7]]

 [[  7   7   7]
  [  7   7   7]
  [  7   7   7]
  ...
  [  7 106   0]
  [  3 101   0]
  [  3 101   2]]

 [[  9   9   9]
  [  9   9   9]
  [  8   8   8]
  ...
  [  2 101   0]
  [  0  97   0]
  [  1  97   0]]

 ...

 [[ 32  32  32]
  [ 33  33  33]
  [ 34  34  34]
  ...
  [ 27 125  16]
  [ 25 123  14]
  [ 20 118   9]]

 [[ 29  29  29]
  [ 37  37  37]
  [ 37  37  37]
  ...
  [ 34 136  27]
  [ 28 130  20]
  [ 37 139  29]]

 [[ 29  29  29]
  [ 37  37  37]
  [ 37  37  37]
  ...
  [ 23 125  16]
  [ 15 117   7]
  [ 23 125  15]]]
