# Introduction to Scikit Learn
Some of most amazing functions of Great scikit-learn Library
00- Import Useful Libraries
01-Getting Data Ready
02-Choose right model
03-Evaluating Model
04-Improve Model
05-Save and Reload Model
06-Putting all together

In [9]:
# Useful Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline 

# 01 Getting Data Ready For ML
3 main Things

1) Split Data into Features and Targets x and Y
2) Filling(Imputing), or Removing the missing Values
3) Convert Non numberical values to numerical Values

In [10]:
heart_disease= pd.read_csv("heart_disease.csv")

In [11]:
heart_disease

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [12]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [13]:
x = heardisease.drop("target",axis=1)

NameError: name 'heardisease' is not defined

In [14]:
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [15]:
y= heardisease["target"]

NameError: name 'heardisease' is not defined

In [16]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [17]:
# Split Data into trainings and Tests

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2)

x_train.shape,x_test.shape,y_train.shape,y_test.shape



((242, 13), (61, 13), (242,), (61,))

In [18]:
 x.shape

(303, 13)

In [19]:
len(heart_disease)

303

# Make Sure its All Numeric Data

In [20]:
carSales=pd.read_csv("car-sales-extended.csv")

In [21]:
carSales.head

<bound method NDFrame.head of        Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]>

In [22]:
len(carSales)

1000

In [23]:
carSales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [24]:
x = carSales.drop("Price",axis=1)
y = carSales["Price"]

In [25]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [26]:
# Build Machine Learning Model

from sklearn.ensemble import RandomForestClassifier

model=RandomForestClassifier()

model.fit (x_train,y_train)

model.score (x_test,y_test)

ValueError: could not convert string to float: 'Toyota'

In [27]:
# Turn Categories into Numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer= ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")

transforme_x =transformer.fit_transform(x)
transforme_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [28]:
pd.DataFrame(transforme_x  

SyntaxError: unexpected EOF while parsing (<ipython-input-28-30bc6d7208eb>, line 1)

In [29]:
dummies=pd.get_dummies(carSales[["Make","Colour","Doors"]])
dummies

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0        4         0           1            0            0             0   
1        5         1           0            0            0             0   
2        4         0           1            0            0             0   
3        4         0           0            0            1             0   
4        3         0           0            1            0             0   
..     ...       ...         ...          ...          ...           ...   
995      4         0           0            0            1             1   
996      3         0           0            1            0             0   
997      4         0           0            1            0             0   
998      4         0           1            0            0             0   
999      4         0           0            0            1             0   

     Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0              0             0           0             1  
1              1             0           0             0  
2              0             0           0             1  
3              0             0           0             1  
4              1             0           0             0  
..           ...           ...         ...           ...  
995            0             0           0             0  
996            0             0           0             1  
997            1             0           0             0  
998            0             0           0             1  
999            1             0           0             0  

[1000 rows x 10 columns]

In [30]:
# Refit the Model
np.random.seed(42)
x_train,x_test,y_train,y_test = train_test_split(transforme_x,y,test_size=0.2)

model.fit(x_train,y_train)

RandomForestClassifier()

In [31]:
x.head()

Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [32]:
model.score(x_test,y_test)

0.0

# Dealing with Missing Values

In [33]:
car_Sales_missing_Values = pd.read_csv("car-sales-extended-missing-data.csv")

In [34]:
car_Sales_missing_Values.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [35]:
car_Sales_missing_Values.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [36]:
#Create Features and Target X,Y

x = car_Sales_missing_Values.drop("Price",axis=1)
y = car_Sales_missing_Values["Price"]

In [37]:
# Turn Categories into Nummbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer= ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")

transforme_x =transformer.fit_transform(x)
transforme_x

ValueError: Input contains NaN

In [ ]:
car_Sales_missing_Values["Doors"].value_counts()

In [ ]:
# Fill The Make Column
car_Sales_missing_Values["Make"].fillna("missing",inplace = True)

#Fill The Colour Column
car_Sales_missing_Values["Colour"].fillna("missing",inplace = True)
#Fill The Doors Column
car_Sales_missing_Values["Doors"].fillna(4,inplace = True)
#Fill Th ODOMETER Column
car_Sales_missing_Values["Odometer (KM)"].fillna(car_Sales_missing_Values["Odometer (KM)"].mean(),inplace = True)



In [38]:
#Checkout Data Frame Again

car_Sales_missing_Values.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [39]:
# Remove Rows with Missing Value

car_Sales_missing_Values.dropna(inplace = True)
car_Sales_missing_Values.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [40]:
len(car_Sales_missing_Values)

773

In [41]:
 #Create Features and Target X,Y

x = car_Sales_missing_Values.drop("Price",axis=1)
y = car_Sales_missing_Values["Price"]

In [42]:
# Turn Categories into Nummbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer= ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")

transforme_x =transformer.fit_transform(car_Sales_missing_Values)
transforme_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

# Fill Missing Values With SciKit Learn

In [43]:
car_Sales_missing_Values = pd.read_csv("car-sales-extended-missing-data.csv")
car_Sales_missing_Values.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [44]:
car_Sales_missing_Values.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

# Drop the rows with No Label

In [45]:
car_Sales_missing_Values.dropna(subset=["Price"],inplace=True)
car_Sales_missing_Values.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [46]:
#Split into X and Y

x = car_Sales_missing_Values.drop("Price",axis =1)
y= car_Sales_missing_Values["Price"]

In [47]:
# Filling Missing Values with SciKet Learn

from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

# Filling Categorical Values with 'Missing' & Numeric Values with Mean

cat_imputer = SimpleImputer(strategy="constant",fill_value = "missing")
door_imputer = SimpleImputer(strategy="constant",fill_value = 4)
num_imputer = SimpleImputer(strategy="mean")


#Define Columns

cat_features = ["Make","Colour"]
door_features = ["Doors"]
num_features = ["Odometer (KM)"]

# Creating an Imputer Something that Fill Missing Values

imputer = ColumnTransformer([
    ("cat_imputer",cat_imputer,cat_features),
     ("door_imputer",door_imputer,door_features),
     ("num_imputer",num_imputer,num_features)
])

# Transform The Data


filled_x = imputer.fit_transform(x)
filled_x



array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [48]:
# Change it to a Data Frame

car_Sales_Filled = pd.DataFrame(filled_x,columns=["Make","Colour","Doors","Odometer (KM)"])

In [49]:
car_Sales_Filled

Make Colour Doors Odometer (KM)
0      Honda  White     4         35431
1        BMW   Blue     5        192714
2      Honda  White     4         84714
3     Toyota  White     4        154365
4     Nissan   Blue     3        181577
..       ...    ...   ...           ...
945   Toyota  Black     4         35820
946  missing  White     3        155144
947   Nissan   Blue     4         66604
948    Honda  White     4        215883
949   Toyota   Blue     4        248360

[950 rows x 4 columns]

In [50]:
car_Sales_Filled.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [51]:
#Now Lets Convert our Data Into Numbers
# Turn Categories into Numbers

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


categorical_features = ["Make","Colour","Doors"]
one_hot = OneHotEncoder()
transformer= ColumnTransformer([("one_hot",one_hot,categorical_features)],remainder="passthrough")

transforme_x =transformer.fit_transform(car_Sales_Filled)
transforme_x


<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>

In [52]:
# Lets fit the Model

np.random.seed(42)


from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test= train_test_split(transforme_x,y, test_size= 0.2 )

model =RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.21990196728583944

In [53]:
len(car_Sales_Filled),len(carSales)

(950, 1000)

# Choossing The Perfect , Right Esitimator/Algorithm for the Problem

ML Model / Algorithm /Estimator

* Classification : Predicting whether a sample is one thing or another

* Regression : Predicting a number

Here you can pick a model for your Regression Problem

https://scikit-learn.org/stable/tutorial/machine_learning_map/index.html


In [54]:
from sklearn.datasets import load_boston
boston =load_boston()

boston

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject


{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [55]:
#Change it to a DataFrame so it could be much easier to view

boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [56]:
boston_dataFrame = pd.DataFrame(boston["data"],columns=boston["feature_names"])
boston_dataFrame["target"] = pd.Series(boston["target"])

boston_dataFrame.head()


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [57]:
len(boston_dataFrame)

506

In [58]:
# Ridge Regression Model


from sklearn.linear_model import Ridge

np.random.seed(42)


# Create the Data

x = boston_dataFrame.drop("target",axis=1)

y = boston_dataFrame["target"]

#Train and Test Data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

# Instantiating the Model

model= Ridge()


model.fit(x_train,y_train)

# Check the score of Ridge on a test Data

model.score(x_test,y_test)

0.6662221670168522

In [59]:
# See If anyOther Algorithm Works betther than this
# Improvve the Model  .
#See if another Algorithm do it better than Riddge
http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
    
    

SyntaxError: invalid syntax (<ipython-input-59-0ee76fcddc2a>, line 4)

In [60]:

## we try the Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

# Setup Random Seed
np.random.seed(44)

# Create Data

x = boston_dataFrame.drop("target",axis=1)
y = boston_dataFrame["target"]

#Split the Data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#Instantiate Random Forest Regressor()

rf = RandomForestRegressor()

rf.fit(x_train, y_train)

# Evaluate The Random Forest Regressor

rf.score(x_test,y_test)





0.891728854028301

In [61]:
# Evaluating both Models and see which one works better
model.score(x_test,y_test)

0.7848289996105058

# Classification Problem
http://scikit-learn.org/stable/tutorial/machine_learning_map/index.html
 

In [62]:
heart_disease = pd.read_csv("heart-disease.csv")

In [63]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [64]:
len(heart_disease)

303

Linear SVC


In [65]:

#Import Linear SVC
from sklearn.svm import LinearSVC

# Setup Random Seed
np.random.seed(42)

# Create Data

x = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

#Split the Data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#Instantiate Linear SVC

lsvc = LinearSVC(max_iter=10000)

lsvc.fit(x_train, y_train)

# Evaluate The Random Forest Regressor

lsvc.score(x_test,y_test)


/Users/faisalhakim/opt/anaconda3/lib/python3.8/site-packages/sklearn/svm/_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.8688524590163934

In [66]:
heart_disease["target"].value_counts()

1    165
0    138
Name: target, dtype: int64

In [67]:
#Import Random Forest Classifier SVC
from sklearn.ensemble import RandomForestClassifier

# Setup Random Seed
np.random.seed(42)

# Create Data

x = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

#Split the Data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#Instantiate Random Forest Classifer 

rfclf = RandomForestClassifier()

rfclf.fit(x_train, y_train)

# Evaluate The Random Forest Regressor

rfclf.score(x_test,y_test)

0.8524590163934426

In [68]:
# Unstructured Data like photo,audio, videos , Use Deep Learning , Transfer Learning
#Structuredd Data , Data Frame use Ensemble Methodds

# Fit The Data / Algorithm on Data , Predictions


In [69]:
# Fitting The Model

#Import Random Forest Classifier SVC
from sklearn.ensemble import RandomForestClassifier

# Setup Random Seed
np.random.seed(42)

# Create Data

x = heart_disease.drop("target",axis=1)
y = heart_disease["target"]

#Split the Data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#Instantiate Random Forest Classifer 

rfclf = RandomForestClassifier()

#Fit the Moddel means (Train model and Find Patterns)

rfclf.fit(x_train, y_train)

# Evaluate The Random Forest Regressor, Using the patterns you already find

rfclf.score(x_test,y_test)

0.8524590163934426

In [70]:
#Make Predictions using a Machine Learning Model

#2 Ways of Prediction

#predict()
#predict_proba()

In [71]:
### Predict()

In [72]:
# Compare Predictions to truth Labels to Evaluate The model

ypreds=rfclf.predict(x_test)

In [73]:
np.mean(ypreds == y_test)

0.8524590163934426

In [74]:
rfclf.score(x_test,y_test)

0.8524590163934426

In [75]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test,ypreds)

0.8524590163934426

In [76]:
# Predict_Proba()   Returns --> Probabilities of a classification Label


In [77]:
rfclf.predict_proba(x_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [78]:
# Predict on the Same Data

rfclf.predict(x_test[:5])

array([0, 1, 1, 0, 1])

In [79]:
x_test[:5]

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
179   57    1   0       150   276    0        0      112      1      0.6   
228   59    1   3       170   288    0        0      159      0      0.2   
111   57    1   2       150   126    1        1      173      0      0.2   
246   56    0   0       134   409    0        0      150      1      1.9   
60    71    0   2       110   265    1        0      130      0      0.0   

     slope  ca  thal  
179      1   1     1  
228      1   0     3  
111      2   1     3  
246      1   2     3  
60       2   1     2

# Evaluating a Model
#.Three ways to evaluate a sklearn, model/Estimator

Estimator sCORE METHOD
The scorinng Parameter
problem specific metric functions


Evaluate a method using score method

# Evaluate a method using score method

In [81]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)


x = heart_disease.drop("target", axis = 1)
y= heart_disease["target"]


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


clf = RandomForestClassifier()

clf.fit(x_train,y_train)

clf.score(x_train,y_train)
clf.score(x_test,y_test)


0.8524590163934426

In [ ]:
#Lets Try RFRegressor


In [82]:
## we try the Random Forest Classifier

from sklearn.ensemble import RandomForestClassifier

# Setup Random Seed
np.random.seed(44)

# Create Data

x = boston_dataFrame.drop("target",axis=1)
y = boston_dataFrame["target"]

#Split the Data
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

#Instantiate Random Forest Regressor()

rf = RandomForestRegressor()

rf.fit(x_train, y_train)

# Evaluate The Random Forest Regressor

rf.score(x_test,y_test)



0.891728854028301

# Evaluating A model using the SCORINNG  parameter


In [92]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)


x = heart_disease.drop("target", axis = 1)
y= heart_disease["target"]


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


clf = RandomForestClassifier()

clf.fit(x_train,y_train)

clf.score(x_test,y_test)

0.8524590163934426

In [93]:
cross_val_score(clf,x,y,cv=5)

array([0.81967213, 0.86885246, 0.81967213, 0.78333333, 0.76666667])

In [94]:
cross_val_score(clf,x,y,cv=10)

array([0.90322581, 0.80645161, 0.87096774, 0.9       , 0.86666667,
       0.8       , 0.73333333, 0.86666667, 0.73333333, 0.8       ])

In [95]:
np.random.seed(42)

#Single Training and test split scoring

clf_single_score = clf.score(x_test,y_test)

#Take the mean of 5 fold crosss validation score

clf_cross_val_score=np.mean(cross_val_score(clf,x,y,cv = 5))

# Compare the two method

clf_single_score, clf_cross_val_score



(0.8524590163934426, 0.8248087431693989)

In [98]:
cross_val_score(clf,x,y,cv=5,scoring=None)

array([0.81967213, 0.86885246, 0.80327869, 0.76666667, 0.8       ])

In [ ]:
Classification Modle Evaluation Metrics


1 Accuracy
2.Area under Roc curve
3.Confusion Matrix
4.classification Report


In [108]:
from sklearn.model_selection import cross_val_score

from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)


x = heart_disease.drop("target", axis = 1)
y= heart_disease["target"]


x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)


clf = RandomForestClassifier()

cross_val_scores=cross_val_score(clf,x,y,cv=5)

In [109]:
np.mean(cross_val_scores)

0.8215300546448088

In [112]:
print(f"Heart disease CrossValid  accuracy: {np.mean(cross_val_scores) *100:.2f}%")

Heart disease CrossValid  accuracy: 82.15%
